-- ALTER TABLE abfrage DROP IF EXISTS ts_insert;
-- ALTER TABLE abfragetyp DROP IF EXISTS ts_insert;
-- ALTER TABLE auto_update DROP IF EXISTS ts_insert;
-- ALTER TABLE besetzung DROP IF EXISTS ts_insert;
-- ALTER TABLE epoche DROP IF EXISTS ts_insert;
-- ALTER TABLE erprobt DROP IF EXISTS ts_insert;
-- ALTER TABLE gattung DROP IF EXISTS ts_insert;
-- ALTER TABLE instrument DROP IF EXISTS ts_insert;
-- ALTER TABLE komponist DROP IF EXISTS ts_insert;
-- ALTER TABLE link DROP IF EXISTS ts_insert;
-- ALTER TABLE link_tmp DROP IF EXISTS ts_insert;
-- ALTER TABLE linktype DROP IF EXISTS ts_insert;
-- ALTER TABLE lookup DROP IF EXISTS ts_insert;
-- ALTER TABLE lookup_type DROP IF EXISTS ts_insert;
-- ALTER TABLE musikstueck DROP IF EXISTS ts_insert;
-- ALTER TABLE musikstueck_besetzung DROP IF EXISTS ts_insert;
-- ALTER TABLE musikstueck_verwendungszweck DROP IF EXISTS ts_insert;
-- ALTER TABLE sammlung DROP IF EXISTS ts_insert;
-- ALTER TABLE sammlung_lookup DROP IF EXISTS ts_insert;
-- ALTER TABLE satz DROP IF EXISTS ts_insert;
-- ALTER TABLE satz_erprobt DROP IF EXISTS ts_insert;
-- ALTER TABLE satz_lookup DROP IF EXISTS ts_insert;
-- ALTER TABLE satz_schwierigkeitsgrad DROP IF EXISTS ts_insert;
-- ALTER TABLE schwierigkeitsgrad DROP IF EXISTS ts_insert;
-- ALTER TABLE standort DROP IF EXISTS ts_insert;
-- ALTER TABLE verwendungszweck DROP IF EXISTS ts_insert;

ALTER TABLE abfrage  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE abfragetyp  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE auto_update  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE besetzung  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE epoche  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE erprobt  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE gattung  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE instrument  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE komponist  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE link  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE link_tmp  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE linktype  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE lookup  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE lookup_type  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE musikstueck  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE musikstueck_besetzung  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE musikstueck_verwendungszweck  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE sammlung  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE sammlung_lookup  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE satz  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE satz_erprobt  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE satz_lookup  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE satz_schwierigkeitsgrad  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE schwierigkeitsgrad  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE standort  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE verwendungszweck  ADD ts_insert datetime DEFAULT CURRENT_TIMESTAMP; 

UPDATE abfrage set ts_insert = '2024-01-01' ;
UPDATE abfragetyp set ts_insert = '2024-01-01' ;
UPDATE auto_update set ts_insert = '2024-01-01' ;
UPDATE besetzung set ts_insert = '2024-01-01' ;
UPDATE epoche set ts_insert = '2024-01-01' ;
UPDATE erprobt set ts_insert = '2024-01-01' ;
UPDATE gattung set ts_insert = '2024-01-01' ;
UPDATE instrument set ts_insert = '2024-01-01' ;
UPDATE komponist set ts_insert = '2024-01-01' ;
UPDATE link set ts_insert = '2024-01-01' ;
UPDATE link_tmp set ts_insert = '2024-01-01' ;
UPDATE linktype set ts_insert = '2024-01-01' ;
UPDATE lookup set ts_insert = '2024-01-01' ;
UPDATE lookup_type set ts_insert = '2024-01-01' ;
UPDATE musikstueck set ts_insert = '2024-01-01' ;
UPDATE musikstueck_besetzung set ts_insert = '2024-01-01' ;
UPDATE musikstueck_verwendungszweck set ts_insert = '2024-01-01' ;
UPDATE sammlung set ts_insert = '2024-01-01' ;
UPDATE sammlung_lookup set ts_insert = '2024-01-01' ;
UPDATE satz set ts_insert = '2024-01-01' ;
UPDATE satz_erprobt set ts_insert = '2024-01-01' ;
UPDATE satz_lookup set ts_insert = '2024-01-01' ;
UPDATE satz_schwierigkeitsgrad set ts_insert = '2024-01-01' ;
UPDATE schwierigkeitsgrad set ts_insert = '2024-01-01' ;
UPDATE standort set ts_insert = '2024-01-01' ;
UPDATE verwendungszweck set ts_insert = '2024-01-01' ;

	
