ALTER TABLE `sammlung` ADD  FOREIGN KEY (`VerlagID`) REFERENCES `verlag`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;#

ALTER TABLE `satz` ADD FOREIGN KEY (`MusikstueckID`) REFERENCES `musikstueck`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `musikstueck` ADD  FOREIGN KEY (`KomponistID`) REFERENCES `komponist`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
