SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- drop view NDB.Musikstuecke

CREATE   VIEW [NDB].[Musikstuecke_V]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 8.1.0.*/
   SELECT 

	m.Name AS Name, 
	m.Nummer AS Nr, 

	v.Name AS Verlag, 
	sa.Name AS Sammlung, 
	--k.Vorname AS Komponist_Vorname, 
	--k.Nachname AS Komponist_Nachname, 
	CONCAT(k.Vorname, ' ', k.Nachname) as Komponist, 
	m.Besetzung,
      sa.ID AS SammlungID, 
       k.ID AS KomponistID,
	   m.ID
   FROM 
      NDB.Musikstueck  AS m 
      LEFT join  NDB.Sammlung  AS sa on m.SammlungID = sa.ID 
      LEFT join  NDB.Komponist  AS k on m.KomponistID = k.ID 
      LEFT join  NDB.Verlag  AS v on sa.VErlagID = v.ID 
   --WHERE 
   --   v.ID = sa.VerlagID AND 
   --   sa.ID = m.SammlungID AND 
   --   k.ID = m.KomponistID

-- ORDER BY m.ID DESC 

--GO

GO
